-- MySQL Script generated by MySQL Workbench
-- Thu Oct  3 23:20:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo_db` DEFAULT CHARACTER SET utf8 ;
USE `todo_db` ;

-- -----------------------------------------------------
-- Table `todo_db`.`BOARD_LIST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo_db`.`BOARD_LIST` ;

CREATE TABLE IF NOT EXISTS `todo_db`.`BOARD_LIST` (
  `board_id` VARCHAR(30) NOT NULL,
  `access_state` TINYINT NOT NULL,
  PRIMARY KEY (`board_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_db`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo_db`.`USER` ;

CREATE TABLE IF NOT EXISTS `todo_db`.`USER` (
  `userid` VARCHAR(20) NOT NULL,
  `board_id` VARCHAR(30) NULL,
  `password` VARCHAR(20) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `admin` TINYINT NULL,
  PRIMARY KEY (`userid`),
  INDEX `fk_USER_BOARD_LIST_idx` (`board_id` ASC),
  UNIQUE INDEX `board_id_UNIQUE` (`board_id` ASC),
  CONSTRAINT `fk_USER_BOARD_LIST`
    FOREIGN KEY (`board_id`)
    REFERENCES `todo_db`.`BOARD_LIST` (`board_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_db`.`BOARD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo_db`.`BOARD` ;

CREATE TABLE IF NOT EXISTS `todo_db`.`BOARD` (
  `board_id` VARCHAR(30) NOT NULL,
  `card_id` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(5) NOT NULL,
  `content` TEXT NOT NULL,
  `file_src` TEXT NULL,
  `prev_card_id` INT NULL,
  PRIMARY KEY (`card_id`),
  INDEX `fk_BOARD_BOARD_LIST1_idx` (`board_id` ASC),
  CONSTRAINT `fk_BOARD_BOARD_LIST1`
    FOREIGN KEY (`board_id`)
    REFERENCES `todo_db`.`BOARD_LIST` (`board_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_db`.`BOARD_AUTH`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo_db`.`BOARD_AUTH` ;

CREATE TABLE IF NOT EXISTS `todo_db`.`BOARD_AUTH` (
  `board_id` VARCHAR(30) NOT NULL,
  `userid` VARCHAR(20) NOT NULL,
  `access_auth` VARCHAR(1) NOT NULL,
  CONSTRAINT `fk_BOARD_AUTH_BOARD_LIST1`
    FOREIGN KEY (`board_id`)
    REFERENCES `todo_db`.`BOARD_LIST` (`board_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo_db`.`BOARD_LOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo_db`.`BOARD_LOG` ;

CREATE TABLE IF NOT EXISTS `todo_db`.`BOARD_LOG` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `board_id` VARCHAR(30) NOT NULL,
  `card` TEXT NOT NULL,
  `userid` VARCHAR(20) NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `prev` VARCHAR(45) NULL,
  `at` VARCHAR(45) NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_BOARD_LOG_BOARD_LIST1_idx` (`board_id` ASC),
  CONSTRAINT `fk_BOARD_LOG_BOARD_LIST1`
    FOREIGN KEY (`board_id`)
    REFERENCES `todo_db`.`BOARD_LIST` (`board_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
